version: "3"

services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 1129:1129
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - rakib_server

    rakib_server:
        build: ./Students
        restart: unless-stopped
        volumes:
            - /home/rakib3004/Desktop/BSSE_1129:usr/src/
        


    
 
        
volumes:
    BSSE_1129:
