version: "3"

services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 789:789
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - shortservice
            - videoservice

    shortservice:
        build: ./Shorts
        restart: unless-stopped
        


    
    videoservice:
        build: ./Videos
        restart: unless-stopped
        
