version: "3"

services:
    nginx:
        image: nginx
        build: .
        restart: unless-stopped
        ports:
            - 100:100
        depends_on:
            - fooddonation
            - foodmanagement
            - foodrequest

    fooddonation:
        build: ./FoodDonation
        restart: unless-stopped
        


    
    foodmanagement:
        build: ./FoodManagement
        restart: unless-stopped
        

    
    foodrequest:
        build: ./FoodRequest
        restart: unless-stopped
 