version: "3"

services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - fooddonation
            - foodmanagement
            - foodrequest

    fooddonation:
        build: ./FoodDonation
        restart: unless-stopped
        


    
    foodmanagement:
        build: ./FoodManagement
        restart: unless-stopped
        

    
    foodrequest:
        build: ./FoodRequest
        restart: unless-stopped
 